# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowInterface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(639, 529)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_specialty = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_specialty.setGeometry(QtCore.QRect(180, 20, 191, 22))
        self.lineEdit_specialty.setObjectName("lineEdit_specialty")
        self.lineEdit_set_year = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_set_year.setGeometry(QtCore.QRect(180, 60, 191, 22))
        self.lineEdit_set_year.setObjectName("lineEdit_set_year")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_qualification = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_qualification.setGeometry(QtCore.QRect(180, 100, 191, 22))
        self.lineEdit_qualification.setObjectName("lineEdit_qualification")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(400, 20, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(30, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_training_period = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_training_period.setGeometry(QtCore.QRect(180, 140, 191, 22))
        self.lineEdit_training_period.setObjectName("lineEdit_training_period")
        self.lineEdit_registration_number = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_registration_number.setGeometry(QtCore.QRect(400, 60, 201, 22))
        self.lineEdit_registration_number.setObjectName("lineEdit_registration_number")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(50, 230, 521, 201))
        self.tableView.setObjectName("tableView")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 240, 250, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton_extramural = QtWidgets.QRadioButton(self.tab)
        self.radioButton_extramural.setGeometry(QtCore.QRect(70, 297, 83, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_extramural.setFont(font)
        self.radioButton_extramural.setObjectName("radioButton_extramural")
        self.radioButton_daytime = QtWidgets.QRadioButton(self.tab)
        self.radioButton_daytime.setGeometry(QtCore.QRect(70, 268, 85, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_daytime.setFont(font)
        self.radioButton_daytime.setObjectName("radioButton_daytime")
        self.radioButton_remotely = QtWidgets.QRadioButton(self.tab)
        self.radioButton_remotely.setGeometry(QtCore.QRect(70, 384, 133, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_remotely.setFont(font)
        self.radioButton_remotely.setObjectName("radioButton_remotely")
        self.radioButton_extramural1 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_extramural1.setGeometry(QtCore.QRect(70, 355, 497, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_extramural1.setFont(font)
        self.radioButton_extramural1.setObjectName("radioButton_extramural1")
        self.radioButton_daytime1 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_daytime1.setGeometry(QtCore.QRect(70, 326, 499, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_daytime1.setFont(font)
        self.radioButton_daytime1.setStatusTip("")
        self.radioButton_daytime1.setShortcut("")
        self.radioButton_daytime1.setCheckable(True)
        self.radioButton_daytime1.setChecked(False)
        self.radioButton_daytime1.setAutoRepeat(False)
        self.radioButton_daytime1.setObjectName("radioButton_daytime1")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(240, 450, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 351, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_specialty_Search = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_specialty_Search.setObjectName("lineEdit_specialty_Search")
        self.gridLayout.addWidget(self.lineEdit_specialty_Search, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit__set_year_search = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit__set_year_search.setObjectName("lineEdit__set_year_search")
        self.gridLayout.addWidget(self.lineEdit__set_year_search, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 50, 151, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableView(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(40, 160, 551, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Год набора:"))
        self.label.setText(_translate("Dialog", "Специальность:"))
        self.label_4.setText(_translate("Dialog", "Квалификация:"))
        self.label_5.setText(_translate("Dialog", "Регистрационный номер:"))
        self.label_6.setText(_translate("Dialog", "Срок обучения:"))
        self.label_3.setText(_translate("Dialog", "Форма получения образования:"))
        self.radioButton_extramural.setText(_translate("Dialog", "Заочная"))
        self.radioButton_daytime.setText(_translate("Dialog", "Дневная"))
        self.radioButton_remotely.setText(_translate("Dialog", "Дистанционная"))
        self.radioButton_extramural1.setText(_translate("Dialog", "Заочная, интегрированная со средним специальным образованием "))
        self.radioButton_daytime1.setText(_translate("Dialog", "Дневная, интегрированная со средним специальным образованием "))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Запись"))
        self.label_7.setText(_translate("Dialog", "Специальность:"))
        self.label_8.setText(_translate("Dialog", "Год набора:"))
        self.pushButton_2.setText(_translate("Dialog", "Найти"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Dialog", "Специальность"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("Dialog", "Год набора"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("Dialog", "квалификаия"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("Dialog", "форма получения образования"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("Dialog", "Срок обучения"))
        # item = self.tableWidget.horizontalHeaderItem(5)
        # item.setText(_translate("Dialog", "Регистрационный номер"))
        # item = self.tableWidget.horizontalHeaderItem(6)
        # item.setText(_translate("Dialog", "Дата регистрации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Поиск"))
